import Head from 'next/head'
import Countries from '../components/countries';
import Pagination from '../components/Pagination';
import Search from '../components/Search';
import { QueryClient } from 'react-query'
import { dehydrate } from 'react-query/hydration'
import { fetchCountries } from '../hooks/useCountries';

const Home = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Search />
      <Countries />
      <Pagination />
    </div>
  )
}

export async function getStaticProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(['countries'], () => fetchCountries())

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}

export default Home;